#!/usr/bin/env python3
"""
Export a public-safe StockArithm Labs repo.

The private repo remains source of truth. This exporter writes an allowlisted
public adapter package, schema docs, frozen sample data, and toy examples.
It intentionally excludes scoring, ranking, state, ledgers, dashboards, and
generated trading algos.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPO_DIR = Path.home() / "Documents" / "work" / "stockarithm-labs"

ADAPTERS = [
    "google_trends.py",
    "fred_series.py",
    "eia_electricity.py",
    "rss_count.py",
    "openchargemap.py",
    "weather_series.py",
    "tsa_table.py",
]

GENERATED_MARKER = "# Generated by sector-rotation-trader/scripts/export_stockarithm_labs.py"
SECRET_DENYLIST = [
    re.compile(r"sk-[A-Za-z0-9_\-]{20,}"),
    re.compile(r"gh[pousr]_[A-Za-z0-9_]{20,}"),
    re.compile(r"xox[baprs]-[A-Za-z0-9\-]{20,}"),
    re.compile(r"AKIA[0-9A-Z]{16}"),
    re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
]


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def _copy_adapter(src_name: str, repo_dir: Path) -> None:
    src = ROOT / "crazy" / "adapters" / src_name
    text = src.read_text()
    text = text.replace("from crazy.config import CRAZY_CACHE_DIR\n", "from stockarithm_labs.cache import DEFAULT_CACHE_DIR\n")
    text = text.replace("from crazy.utils import cached_fetch\n", "from stockarithm_labs.cache import cached_fetch\n")
    text = text.replace("CRAZY_CACHE_DIR", "DEFAULT_CACHE_DIR")
    dst = repo_dir / "stockarithm_labs" / "adapters" / src_name
    _write(dst, f"{GENERATED_MARKER}\n{text}")


def _write_package(repo_dir: Path) -> None:
    _write(repo_dir / "stockarithm_labs" / "__init__.py", f'{GENERATED_MARKER}\n__version__ = "0.1.0"\n')
    _write(
        repo_dir / "stockarithm_labs" / "adapters" / "__init__.py",
        f"""{GENERATED_MARKER}
from .eia_electricity import fetch_eia_electricity
from .fred_series import fetch_fred_series
from .google_trends import fetch_google_trends
from .openchargemap import fetch_openchargemap_counts
from .rss_count import fetch_rss_counts
from .tsa_table import fetch_tsa_table
from .weather_series import fetch_weather_series

__all__ = [
    "fetch_eia_electricity",
    "fetch_fred_series",
    "fetch_google_trends",
    "fetch_openchargemap_counts",
    "fetch_rss_counts",
    "fetch_tsa_table",
    "fetch_weather_series",
]
""",
    )
    _write(
        repo_dir / "stockarithm_labs" / "cache.py",
        f"""{GENERATED_MARKER}
from __future__ import annotations

import json
import os
from datetime import datetime, timedelta
from pathlib import Path
from typing import Callable, TypeVar


DEFAULT_CACHE_DIR = os.getenv("STOCKARITHM_CACHE_DIR", ".cache/stockarithm-labs")
T = TypeVar("T")


def cached_fetch(cache_path: str | os.PathLike[str], ttl_hours: int, fetch_fn: Callable[[], T]) -> T:
    path = Path(cache_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.utcnow()
    if path.exists():
        try:
            payload = json.loads(path.read_text())
            fetched_at = payload.get("fetched_at")
            if fetched_at and now - datetime.fromisoformat(fetched_at) < timedelta(hours=ttl_hours):
                return payload.get("data")
        except Exception:
            pass
    data = fetch_fn()
    path.write_text(json.dumps({{"fetched_at": now.isoformat(), "data": data}}, indent=2, default=str))
    return data
""",
    )
    for adapter in ADAPTERS:
        _copy_adapter(adapter, repo_dir)


def _write_router(repo_dir: Path) -> None:
    _write(
        repo_dir / "stockarithm_labs" / "adapter_router.py",
        f"""{GENERATED_MARKER}
from __future__ import annotations


ADAPTER_KEYWORDS = {{
    "google_trends": ["google trends", "search interest", "search volume", "trends"],
    "rss_count": ["rss", "feed", "news feed", "news volume", "article count"],
    "fred_series": ["fred", "federal reserve", "economic data", "series id"],
    "eia_electricity": ["eia", "electricity", "power demand", "grid demand"],
    "openchargemap": ["openchargemap", "ev charger", "charging station", "ev station"],
    "tsa_table": ["tsa", "passenger", "throughput", "airport"],
    "weather_series": ["weather", "temperature", "precipitation", "heat", "cold"],
}}

MIN_SCORE = 2


def score_text(text: str) -> dict[str, int]:
    text_l = text.lower()
    scores: dict[str, int] = {{}}
    for adapter, keywords in ADAPTER_KEYWORDS.items():
        score = 0
        for keyword in keywords:
            if keyword in text_l:
                score += 2 if " " in keyword else 1
        if score:
            scores[adapter] = score
    return scores


def route_text(text: str) -> list[str]:
    scores = score_text(text)
    if not scores:
        return []
    max_score = max(scores.values())
    if max_score < MIN_SCORE:
        return []
    return sorted(adapter for adapter, score in scores.items() if score == max_score)


if __name__ == "__main__":
    import json
    import sys

    text = " ".join(sys.argv[1:]) or sys.stdin.read()
    print(json.dumps({{"adapters": route_text(text), "scores": score_text(text)}}, indent=2))
""",
    )


def _write_schemas(repo_dir: Path) -> None:
    adapter_output = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "StockArithm Adapter Output",
        "type": "object",
        "required": ["adapter", "rows"],
        "properties": {
            "adapter": {"type": "string"},
            "source": {"type": "string"},
            "generated_at": {"type": "string", "format": "date-time"},
            "rows": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": ["date"],
                    "properties": {
                        "date": {"type": "string"},
                        "value": {"type": ["number", "null"]},
                        "count": {"type": ["number", "null"]},
                        "interest": {"type": ["number", "null"]},
                    },
                    "additionalProperties": True,
                },
            },
        },
        "additionalProperties": True,
    }
    adapter_manifest = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "StockArithm Adapter Manifest",
        "type": "object",
        "required": ["name", "function", "columns", "requires_key"],
        "properties": {
            "name": {"type": "string"},
            "function": {"type": "string"},
            "columns": {"type": "array", "items": {"type": "string"}},
            "requires_key": {"type": "boolean"},
            "source_url": {"type": "string"},
        },
    }
    _write(repo_dir / "schemas" / "adapter_output.schema.json", json.dumps(adapter_output, indent=2) + "\n")
    _write(repo_dir / "schemas" / "adapter_manifest.schema.json", json.dumps(adapter_manifest, indent=2) + "\n")


def _write_samples(repo_dir: Path) -> None:
    _write(
        repo_dir / "samples" / "google_trends_urgent_home_repair.csv",
        "date,interest\n2026-05-01,42\n2026-05-08,47\n2026-05-15,55\n2026-05-22,63\n2026-05-29,59\n",
    )
    _write(
        repo_dir / "samples" / "tsa_throughput.csv",
        "date,throughput,throughput_yoy,yoy_pct\n2026-05-26,2450000,2320000,0.0560\n2026-05-27,2510000,2390000,0.0502\n2026-05-28,2600000,2460000,0.0569\n",
    )
    _write(
        repo_dir / "samples" / "fred_series.csv",
        "date,value\n2026-05-09,224000\n2026-05-16,226000\n2026-05-23,229000\n2026-05-30,231000\n",
    )


def _write_examples(repo_dir: Path) -> None:
    _write(
        repo_dir / "examples" / "toy_signal_from_sample.py",
        f"""{GENERATED_MARKER}
from __future__ import annotations

import pandas as pd


def toy_signal(path: str = "samples/google_trends_urgent_home_repair.csv") -> str:
    df = pd.read_csv(path)
    if len(df) < 4:
        return "HOLD"
    latest = float(df["interest"].iloc[-1])
    trailing_mean = float(df["interest"].iloc[-4:-1].mean())
    return "WATCH" if latest > trailing_mean * 1.10 else "HOLD"


if __name__ == "__main__":
    print(toy_signal())
""",
    )
    _write(
        repo_dir / "examples" / "fetch_google_trends.py",
        f"""{GENERATED_MARKER}
from stockarithm_labs.adapters import fetch_google_trends


if __name__ == "__main__":
    df = fetch_google_trends("urgent home repair", days_back=90)
    print(df.tail())
""",
    )


def _write_docs(repo_dir: Path) -> None:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    _write(
        repo_dir / "README.md",
        f"""# StockArithm Labs

Public adapter lab for StockArithm.

This repo shows how messy public data sources become normalized signal inputs.
It does **not** include StockArithm scoring, ranking, promotion rules, live trade
logic, private state, or paid artifacts.

Generated from the private source repo at `{generated_at}`.

## What is included

- Public-safe adapters in `stockarithm_labs/adapters/`
- Adapter routing helper in `stockarithm_labs/adapter_router.py`
- Output schemas in `schemas/`
- Frozen sample data in `samples/`
- Toy examples in `examples/`

## What is intentionally excluded

- Strategy scoring and ranking logic
- Algo registry internals
- Live portfolio state
- Paid signal detail
- Private dashboards and ledgers
- Any DBB2 code or archetype logic

## Quickstart

```bash
python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
python examples/toy_signal_from_sample.py
```

Some adapters call public APIs. Those may require optional keys such as
`FRED_API_KEY`, `EIA_API_KEY`, or `OPENCHARGEMAP_API_KEY`.
""",
    )
    _write(
        repo_dir / "docs" / "ADAPTER_CONTRACT.md",
        """# Adapter Contract

Adapters return a pandas DataFrame. They should fail closed by returning an
empty DataFrame instead of raising network or schema exceptions.

Required conventions:

- `date` column is always present when rows exist.
- The primary observed value is named consistently: `value`, `count`,
  `interest`, `throughput`, or another documented metric.
- Adapter functions should not contain trading rules.
- Adapter functions should not know about ranking, promotion, or portfolio
  state.

This makes adapters reusable as public data-ingestion primitives while keeping
the product's scoring engine private.
""",
    )
    _write(
        repo_dir / "docs" / "NIGHTLY_SYNC.md",
        """# Nightly Sync

This repository is generated from an allowlist in the private StockArithm source
repo. Treat generated files as downstream artifacts.

The exporter:

1. Rewrites private package imports.
2. Copies only approved adapters and docs.
3. Writes sample/frozen data and toy examples.
4. Runs a denylist scan for obvious secret patterns.
5. Optionally commits and pushes this public repo.

Do not hand-edit generated files unless the change is meant to be overwritten.
""",
    )
    _write(repo_dir / "requirements.txt", "pandas>=2.0.0\nrequests>=2.31.0\nbeautifulsoup4>=4.12.0\npytrends>=4.9.2\nfeedparser>=6.0.0\nfredapi>=0.5.1\n")
    _write(repo_dir / ".gitignore", ".venv/\n__pycache__/\n*.pyc\n.cache/\n.DS_Store\n")


def _scan_for_secrets(repo_dir: Path) -> None:
    hits: list[str] = []
    for path in repo_dir.rglob("*"):
        if not path.is_file() or ".git" in path.parts:
            continue
        try:
            text = path.read_text(errors="ignore")
        except Exception:
            continue
        for pattern in SECRET_DENYLIST:
            if pattern.search(text):
                hits.append(str(path.relative_to(repo_dir)))
                break
    if hits:
        raise SystemExit("secret scan failed: " + ", ".join(sorted(hits)))


def _git(repo_dir: Path, args: list[str]) -> None:
    subprocess.run(["git", *args], cwd=repo_dir, check=True)


def export(repo_dir: Path, push: bool = False, remote_url: str | None = None) -> None:
    repo_dir.mkdir(parents=True, exist_ok=True)
    for name in ["stockarithm_labs", "schemas", "samples", "examples", "docs"]:
        path = repo_dir / name
        if path.exists():
            shutil.rmtree(path)

    _write_package(repo_dir)
    _write_router(repo_dir)
    _write_schemas(repo_dir)
    _write_samples(repo_dir)
    _write_examples(repo_dir)
    _write_docs(repo_dir)
    _scan_for_secrets(repo_dir)

    if not (repo_dir / ".git").exists():
        _git(repo_dir, ["init"])
        _git(repo_dir, ["symbolic-ref", "HEAD", "refs/heads/main"])
    if remote_url:
        remotes = subprocess.check_output(["git", "remote"], cwd=repo_dir, text=True).splitlines()
        if "origin" in remotes:
            _git(repo_dir, ["remote", "set-url", "origin", remote_url])
        else:
            _git(repo_dir, ["remote", "add", "origin", remote_url])
    _git(repo_dir, ["add", "."])
    status = subprocess.check_output(["git", "status", "--porcelain"], cwd=repo_dir, text=True).strip()
    if status:
        _git(repo_dir, ["config", "user.name", "stockarithm-labs-bot"])
        _git(repo_dir, ["config", "user.email", "stockarithm-labs-bot@users.noreply.github.com"])
        _git(repo_dir, ["commit", "-m", f"sync public adapter lab {datetime.now(timezone.utc).strftime('%Y-%m-%d')}"])
    if push:
        _git(repo_dir, ["push", "-u", "origin", "main"])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-dir", default=str(DEFAULT_REPO_DIR))
    parser.add_argument("--remote-url", default="")
    parser.add_argument("--push", action="store_true")
    args = parser.parse_args()
    export(Path(args.repo_dir).expanduser(), push=args.push, remote_url=args.remote_url or None)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
