"""
Morning content email — sends today's Substack draft to the operator.

Reads drafts/YYYY-MM-DD.md (generated by post_generator.py) and
emails the full text so the operator can review and copy-paste to
Substack in under 5 minutes.

Usage:
    AFH_RUN_DATE=2026-04-21 python scripts/morning_content_email.py
    python scripts/morning_content_email.py  # defaults to today
"""

from __future__ import annotations

import os
import sys
from datetime import date, timedelta
from pathlib import Path


DRAFTS_DIR = Path("drafts")


def _run_date() -> str:
    env = os.getenv("AFH_RUN_DATE", "").strip()
    if env:
        return env
    return date.today().isoformat()


def main():
    run_date = _run_date()
    draft_path = DRAFTS_DIR / f"{run_date}.md"
    event_dir = DRAFTS_DIR / "linkedin_events" / run_date

    lines = []
    lines.append(f"CONTENT DRAFT — {run_date}")
    lines.append("=" * 50)

    if not draft_path.exists():
        lines.append("")
        lines.append(f"No draft found for {run_date}.")
        lines.append(f"Expected: {draft_path}")
        lines.append("")
        lines.append("post_generator.py may not have run yet, or the deep validation")
        lines.append("report was missing for this date.")
        print("\n".join(lines))
        return

    draft = draft_path.read_text().strip()
    lines.append("")
    lines.append(draft)
    lines.append("")
    lines.append("=" * 50)
    if event_dir.exists():
        event_posts = sorted(event_dir.glob("*.md"))
        if event_posts:
            lines.append("")
            lines.append("LINKEDIN EVENT DRAFTS")
            lines.append("=" * 50)
            for path in event_posts:
                lines.append("")
                lines.append(f"--- {path.name} ---")
                lines.append(path.read_text().strip())
    lines.append("")
    lines.append("To publish: copy above, paste into Substack, review, hit send.")
    lines.append(f"Draft file: {draft_path}")
    if event_dir.exists():
        lines.append(f"LinkedIn event drafts: {event_dir}")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
